"""Init

Revision ID: ef9b1fcc0aca
Revises: b9c346640aa3
Create Date: 2023-07-04 17:00:46.473901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9b1fcc0aca'
down_revision = 'b9c346640aa3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
